m2m-relations/articles/urls.py
from django.urls import path

from articles.views import articles_list

urlpatterns = [
    path('', articles_list, name='articles'),
]

m2m-relations/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

m2m-relations/articles/models.py
from django.db import models


class Tag(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название')

    def __str__(self):
        return self.title


class Scope(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    is_main = models.BooleanField(default=False)

    class Meta:
        ordering = ['is_main']


class Article(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название')
    text = models.TextField(verbose_name='Текст')
    published_at = models.DateTimeField(verbose_name='Дата публикации')
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение', )
    tags = models.ManyToManyField(Tag, related_name='articles', through=Scope)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title

m2m-relations/articles/views.py
from django.shortcuts import render

from articles.models import Article


def articles_list(request):
    template = 'articles/news.html'
    ordering = '-published_at'
    articles = Article.objects.order_by(ordering).prefetch_related('tags')
    context = {
        'object_list': articles,
    }
    # используйте этот параметр для упорядочивания результатов
    # https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.order_by
    return render(request, template, context)

m2m-relations/templates/articles/base.html
{% load static %}

<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Bootstrap core CSS -->
  <link href="{% static  "css/bootstrap.min.css" %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static  "css/3-col-portfolio.css" %}" rel="stylesheet">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Будь в курсе событий</a>
  </div>
</nav>

<div class="container">{% block content %}{% endblock %}</div>

<!--JavaScript at end of body for optimized loading-->
<script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
<!-- Bootstrap core JavaScript -->
<script src="{% static  "js/jquery.min.js" %}"></script>
</body>
</html>

m2m-relations/templates/articles/news.html
{% extends "articles/base.html" %}

{% load static %}

{% block title %}Новости{% endblock %}

{% block content %}
<div class="row">
    {% for article in object_list %}
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="{% get_media_prefix %}{{ article.image }}" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">{{ article.title }}</a>
                </h4>
                <p class="card-text">{{ article.text }}</p>
                {% for scope in article.scope_set.all reversed %}
                <span class="badge {% if scope.is_main %}badge-primary{% else %}badge-secondary{% endif %}">{{ scope.tag.title}}</span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}